version: "3.8"

services:
  gitlib:
    container_name: gitlab
    image: "gitlab/gitlab-ce:14.1.3-ce.0"
    hostname: "localhost"
    privileged: true
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url='https://localhost' 
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - "gitlab_14.1.3_config:/etc/gitlab"
      - "gitlab_14.1.3_logs:/var/log/gitlab"
      - "gitlab_14.1.3_data:/var/opt/gitlab"
    networks:
      - jenkins

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    user: root
    hostname: localhost
    privileged: true
    environment:
      - DOCKER_HOST=tcp://localhost:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_TLS_VERIFY=1
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    networks:
      - jenkins

volumes:
  gitlab_14.1.3_config:
    external: true
  gitlab_14.1.3_logs:
    external: true
  gitlab_14.1.3_data:
    external: true
  jenkins-data:
    external: true
  jenkins-docker-certs:
    external: true

networks:
  jenkins:
    external: true
