version: "3.8"

services:
  jenkins_blueocean:
    container_name: jenkins
    image: "jenkinsci/blueocean"
    user: root
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - "jenkins"

volumes:
  jenkins_data:
    external:
      true

networks:
  jenkins:
    external:
      true